# Global configuration setting for VisualRL

# ------------------------General parameters------------------------
exp_name: "Reproduce-ReacherEasy"

# set as -1 for random seed
seed: 2023

# set as -1 for cpu training
gpu: 1
# ---------------------------Environment---------------------------
env: "reacher-easy"
camera_id: 0
time_limit: 1000
# -----------------------------Training-----------------------------
total_steps: 1000000
collect_steps: 1000
# ------------------------Saving and logging------------------------
# We recommend evaluating the agent every 25k steps for PlaNet, and every 10k steps for other agents.
eval_freq: 10000
eval_episodes: 10
save_video: False

save_tb: True
log_interval: 100

save_data: False
save_data_interval: 100000

save_checkpoint: False
save_checkpoint_interval: 100000

# Recommended action repeat: 2 for Walker, Finger, 4 for Reacher, Cheetah, Ball in cup, 8 for Cartpole