hidden_dim: 256
discount: 0.99
init_temperature: 0.01
alpha_lr: 1e-3
alpha_beta: 0.9
actor_lr: 1e-3
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2
critic_lr: 1e-3
critic_beta: 0.9
critic_tau: 0.005
critic_target_update_freq: 2
encoder_type: 'pixel'
encoder_feature_dim: 50
encoder_tau: 0.005
encoder_lr: 1e-3
decoder_lr: 1e-3
decoder_update_freq: 1
decoder_latent_lambda: 0.0
decoder_weight_lambda: 0.0
num_layers: 4
num_filters: 32
bisim_coef: 0.5
builtin_encoder: True